# Generated by Django 5.2.6 on 2025-09-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait')], default='DEPOT', max_length=10, verbose_name="Type d'opération")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
