# Generated by Django 5.2.6 on 2025-09-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Saving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldeGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
